这是一个报错收集，



##### 主机无法工作的报错:

```json
2019-01-07 08:13:39,732+08 ERROR [org.ovirt.engine.core.bll.InitVdsOnUpCommand] (EE-ManagedThreadFactory-engine-Thread-2402) [5e5233b6] Could not connect host 'host91' to pool 'datacenter1': null
```



##### 挂载nfs超时或者无route

一般每个主机都应该有共享目录的，这样虚拟机才能正常开机，但是挂载可能因为源主机防火墙配置，导致挂载超时或者失败

```json
2019-01-07 08:17:07,427+08 ERROR [org.ovirt.engine.core.dal.dbbroker.auditloghandling.AuditLogDirector] (EE-ManagedThreadFactory-engineScheduled-Thread-54) [48d487ac] EVENT_ID: VDS_STORAGES_CONNECTION_FAILED(188), Failed to connect Host host91 to the Storage Domains data89.
2019-01-07 08:17:07,427+08 INFO  [org.ovirt.engine.core.vdsbroker.vdsbroker.ConnectStorageServerVDSCommand] (EE-ManagedThreadFactory-engineScheduled-Thread-54) [48d487ac] FINISH, ConnectStorageServerVDSCommand, return: {84833af7-192c-40ef-9c10-646ca50c40ee=477}, log id: 3c7cc259
2019-01-07 08:17:07,431+08 ERROR [org.ovirt.engine.core.dal.dbbroker.auditloghandling.AuditLogDirector] (EE-ManagedThreadFactory-engineScheduled-Thread-54) [48d487ac] EVENT_ID: STORAGE_DOMAIN_ERROR(996), The error message for connection 192.168.0.89:/export/data returned by VDSM was: Problem while trying to mount target
2019-01-07 08:17:07,431+08 ERROR [org.ovirt.engine.core.bll.storage.connection.FileStorageHelper] (EE-ManagedThreadFactory-engineScheduled-Thread-54) [48d487ac] The connection with details '192.168.0.89:/export/data' failed because of error code '477' and error message is: problem while trying to mount target
```

#####  主机掉线

主机掉线以后，engine会尝试连接，但是如果主机一直不在线，那么就会报错

```shell
2019-01-07 08:55:35,640+08 INFO  [org.ovirt.vdsm.jsonrpc.client.reactors.ReactorClient] (SSL Stomp Reactor) [] Connecting to /192.168.0.91
2019-01-07 08:55:38,646+08 ERROR [org.ovirt.engine.core.vdsbroker.vdsbroker.GetAllVmStatsVDSCommand] (EE-ManagedThreadFactory-engineScheduled-Thread-26) [] Command 'GetAllVmStatsVDSCommand(HostName = host91, VdsIdVDSCommandParametersBase:{hostId='f42796d3-fa7d-46d8-a8af-617158a8cbe1'})' execution failed: java.net.NoRouteToHostException: No route to host
```

如果连接过程中无故突然掉线还会引发下面的错误

```shell
2019-01-07 08:59:36,992+08 ERROR [org.ovirt.vdsm.jsonrpc.client.reactors.ReactorClient] (EE-ManagedThreadFactory-engine-Thread-446) [328947bc] Exception during connection
2019-01-07 08:59:36,993+08 ERROR [org.ovirt.engine.core.vdsbroker.vdsbroker.ConnectStoragePoolVDSCommand] (EE-ManagedThreadFactory-engine-Thread-446) [328947bc] Command 'ConnectStoragePoolVDSCommand(HostName = host91, ConnectStoragePoolVDSCommandParameters:{hostId='f42796d3-fa7d-46d8-a8af-617158a8cbe1', vdsId='f42796d3-fa7d-46d8-a8af-617158a8cbe1', storagePoolId='be3626c6-36fa-4656-ab48-3d337775db84', masterVersion='1'})' execution failed: java.rmi.ConnectException: Connection timeout
2019-01-07 08:59:36,993+08 INFO  [org.ovirt.engine.core.vdsbroker.vdsbroker.ConnectStoragePoolVDSCommand] (EE-ManagedThreadFactory-engine-Thread-446) [328947bc] FINISH, ConnectStoragePoolVDSCommand, log id: 5047018b
2019-01-07 08:59:36,993+08 ERROR [org.ovirt.engine.core.bll.InitVdsOnUpCommand] (EE-ManagedThreadFactory-engine-Thread-446) [328947bc] Could not connect host 'host91' to pool 'datacenter1': null
2019-01-07 08:59:36,994+08 ERROR [org.ovirt.engine.core.vdsbroker.vdsbroker.GetAllVmStatsVDSCommand] (EE-ManagedThreadFactory-engineScheduled-Thread-45) [] Command 'GetAllVmStatsVDSCommand(HostName = host91, VdsIdVDSCommandParametersBase:{hostId='f42796d3-fa7d-46d8-a8af-617158a8cbe1'})' execution failed: VDSGenericException: VDSNetworkException: Connection issue Connection timeout
2019-01-07 08:59:36,995+08 INFO  [org.ovirt.engine.core.vdsbroker.monitoring.PollVmStatsRefresher] (EE-ManagedThreadFactory-engineScheduled-Thread-45) [] Failed to fetch vms info for host 'host91' - skipping VMs monitoring.
2019-01-07 08:59:36,995+08 INFO  [org.ovirt.engine.core.vdsbroker.vdsbroker.SetVmTicketVDSCommand] (default task-16) [3695f0e5] Command 'org.ovirt.engine.core.vdsbroker.vdsbroker.SetVmTicketVDSCommand' return value 'StatusOnlyReturn [status=Status [code=5022, message=Connection issue Connection timeout]]'
2019-01-07 08:59:36,995+08 INFO  [org.ovirt.engine.core.vdsbroker.vdsbroker.SetVmTicketVDSCommand] (default task-16) [3695f0e5] HostName = host91
2019-01-07 08:59:36,996+08 ERROR [org.ovirt.engine.core.vdsbroker.vdsbroker.SetVmTicketVDSCommand] (default task-16) [3695f0e5] Command 'SetVmTicketVDSCommand(HostName = host91, SetVmTicketVDSCommandParameters:{hostId='f42796d3-fa7d-46d8-a8af-617158a8cbe1', vmId='765b97f7-86b2-45c2-858d-1e4c22d9e293', protocol='SPICE', ticket='uOFYTSQ/soxd', validTime='120', userName='admin', userId='c4948d78-11db-11e9-aa50-001a4a160101', disconnectAction='LOCK_SCREEN'})' execution failed: VDSGenericException: VDSNetworkException: Connection issue Connection timeout

```

